CREATE OR REPLACE DATABASE ECOMM_DB;
USE DATABASE ECOMM_DB;
CREATE SCHEMA IF NOT EXISTS ECOMM;
USE SCHEMA ECOMM;
CREATE OR REPLACE STAGE SNOWFLAKE_KAFKA_STAGE;


CREATE OR REPLACE TABLE USERS (
    USER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    DESCRIPTION STRING,
    PRICE NUMBER(10, 2),
    STOCK_QUANTITY NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    USER_ID NUMBER,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    PRICE NUMBER(10, 2)
);

GRANT USAGE ON DATABASE ECOMM_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA ECOMM_DB.ECOMM TO ROLE ACCOUNTADMIN;
GRANT INSERT ON ALL TABLES IN SCHEMA ECOMM_DB.ECOMM TO ROLE ACCOUNTADMIN;
